DS-AEON/back-end

- build.gradle
- src/main/java/com/aeon/hadog/base/Enum/VoiceAge.java
- src/main/java/com/aeon/hadog/domain/DogName.java
- src/main/java/com/aeon/hadog/domain/Emotion.java
- src/main/java/com/aeon/hadog/domain/ShelterPost.java
- src/main/java/com/aeon/hadog/domain/Voice.java
- src/main/resources/application.properties
- Voice 테이블: 성별 부분은 Enum으로 받으면 좋을 것 같아 자료형 수정했습니다.
- ShelterPost 테이블: 포인핸드의 공고글 참고하여 erd 수정 후, 테이블 생성했습니다.
> Feat: DB 연결 및 테이블 생성

- src/main/java/com/aeon/hadog/base/config/security/JwtTokenProvider.java
- src/main/resources/application.properties
- application.properties 파일에서 secretkey 정의
> Refactor: secretKey 수정

- build.gradle
- src/main/java/com/aeon/hadog/base/dto/user/JoinRequestDTO.java
- src/main/java/com/aeon/hadog/controller/UserController.java
- src/main/java/com/aeon/hadog/service/UserService.java
- 이름, 아이디, 비밀번호, 닉네임, 이메일 필수 입력
- 아이디는 5~16자 영문 대소문자와 숫자만 가능
- 비밀번호는 8~16자 영문 대소문자와 숫자, 특수문자 가능
- 닉네임은 특수문제를 제외한 2~10자리 문자
> Refactor: 비밀번호 유효성 검사

- src/main/java/com/aeon/hadog/base/config/security/JwtAuthenticationFilter.java
- src/main/java/com/aeon/hadog/base/config/security/JwtTokenProvider.java
- src/main/resources/application.properties
> Style: Slf4j를 이용하여 로그 남김

- src/main/java/com/aeon/hadog/base/code/ErrorCode.java
- src/main/java/com/aeon/hadog/base/dto/diary/DiaryDTO.java
- src/main/java/com/aeon/hadog/base/dto/diary/UploadDiaryDTO.java
- src/main/java/com/aeon/hadog/base/exception/BlanckContentException.java
- src/main/java/com/aeon/hadog/base/exception/DiaryNotFoundException.java
- src/main/java/com/aeon/hadog/base/exception/EmotionTrackNotBelongToUserException.java
- src/main/java/com/aeon/hadog/base/exception/EmotionTrackNotFoundException.java
- src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
- src/main/java/com/aeon/hadog/controller/DiaryController.java
- src/main/java/com/aeon/hadog/domain/Diary.java
- src/main/java/com/aeon/hadog/domain/EmotionTrack.java
- src/main/java/com/aeon/hadog/repository/DiaryRepository.java
- src/main/java/com/aeon/hadog/repository/EmotionTrackRepository.java
- src/main/java/com/aeon/hadog/repository/PetRepository.java
- src/main/java/com/aeon/hadog/service/DiaryService.java
다이어리 작성 기능, 상세 보기 기능, 수정 기능 추가했습니다. 
기능 개발 및 ErrorCode 추가했습니다. 
#21 #22  #23 
Diary와 User의 연관성이 너무 적어서 코드가 복잡해집니다.
Diary에서 EmotionTrack을 찾고, EmotionTrack에서 PetId를 통해 Pet을 찾아, User를 찾아야 합니다.
Diary 엔티티 수정이 필요할 듯 합니다..
> Diary 작성, 상세, 수정 기능 추가

- src/main/java/com/aeon/hadog/base/code/ErrorCode.java
- src/main/java/com/aeon/hadog/base/exception/PetIdNotFoundException.java
- src/main/java/com/aeon/hadog/controller/PetController.java
- src/main/java/com/aeon/hadog/service/PetService.java
> Refactor: Pet 오류처리

- src/test/java/com/aeon/hadog/controller/PetControllerTest.java
- src/test/java/com/aeon/hadog/service/PetServiceTest.java
Pet Controller, Service 테스트 코드 수정
* 반려견 성별 변수를 boolean에서 varchar로 변경하여 생긴 오류 수정
* S3 연결을 통해 바뀐 Controller 코드에 따라 테스트 코드 수정(@RequestPart, form-data 형식 등)
지속적인 오류가 발생하기 때문에 함께 봐주어 수정하면 좋을 것 같습니다!
> Refactor: 반려견 테스트 코드 수정

- src/main/java/com/aeon/hadog/base/code/ErrorCode.java
- src/main/java/com/aeon/hadog/base/config/security/SecurityConfiguration.java
- src/main/java/com/aeon/hadog/base/dto/shelter/ListShelterPostDTO.java
- src/main/java/com/aeon/hadog/base/dto/shelter/ShelterPostDTO.java
- src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
- src/main/java/com/aeon/hadog/base/exception/ShelterPostNotFoundException.java
- src/main/java/com/aeon/hadog/controller/ShelterPostController.java
- src/main/java/com/aeon/hadog/domain/ShelterPostImages.java
- src/main/java/com/aeon/hadog/repository/ShelterPostImagesRepository.java
- src/main/java/com/aeon/hadog/repository/ShelterPostRepository.java
- src/main/java/com/aeon/hadog/service/AmazonS3Service.java
- src/main/java/com/aeon/hadog/service/ShelterPostService.java
Shelter 작성, 상세, 목록 기능 구현했습니다.
- 공고 작성 기능 테스트를 위해, security 일단 전부 허용했습니다. 추후 수정 필요합니다.
- 목록 기능 페이지네이션하여 15개의 데이터만 불러올 수 있도록 했습니다.
#35, #36, #37
- 공고 작성 기능의 권한을 어떻게 부여해야할지 논의 필요합니다.
> Shelter 작성, 상세, 목록 기능 구현

- build.gradle
- src/main/java/com/aeon/hadog/base/dto/shelter/ShelterPostDTO.java
- src/main/java/com/aeon/hadog/controller/ShelterPostController.java
- src/main/java/com/aeon/hadog/service/ShelterPostService.java
- src/test/java/com/aeon/hadog/controller/ShelterPostControllerTest.java
- src/test/java/com/aeon/hadog/service/ShelterPostServiceTest.java
Shelter 기능에 대한 Controller Test 및 Service Test 완료했습니다. 
Controller는 성공 시나리오로 테스트 진행했고, Service는 실패 시나리오를 작성하여 진행했습니다.
#41  #42
> Shelter Controller Test 및 Service Test

- src/test/java/com/aeon/hadog/service/UserServiceTest.java
UserSerivce 실패 케이스 추가
Service Test에서 실패 시나리오를 작성하여 진행했습니다.
#47
> Test: UserSerivce 실패 케이스 추가

- src/main/java/com/aeon/hadog/base/dto/comment/CommentDTO.java
- src/main/java/com/aeon/hadog/controller/CommentController.java
- src/main/java/com/aeon/hadog/domain/ShelterPostComment.java
- src/main/java/com/aeon/hadog/repository/ShelterPostCommentRepository.java
- src/main/java/com/aeon/hadog/service/ShelterPostCommentService.java
대댓글 작성 기능
대댓글 작성 기능 추가했습니다.
#44 
댓글 조회 시 parentComment 부분 무한루프 오류가 있어 수정이 필요합니다.
> Feat: 대댓글 작성

- src/main/java/com/aeon/hadog/controller/MyPageController.java
- src/main/java/com/aeon/hadog/service/MyPageService.java
postman 테스트 시 오류나서 닉네임 반환 수정하였습니다. 
import만 수정한 것이라 머지 하겠습니다 .
> feat:닉네임 ì반환 수정

- src/main/java/com/aeon/hadog/base/dto/comment/CommentDTO.java
- src/main/java/com/aeon/hadog/controller/CommentController.java
- src/main/java/com/aeon/hadog/service/ShelterPostCommentService.java
대댓글 기능 수정
API 반환값에서 체인처럼 무한으로 댓글정보가 생성되는 오류를 수정하였습니다. (DTO 반환)
#52
> Feat: 대댓글 기능 수정 및 추가

- src/main/java/com/aeon/hadog/base/code/ErrorCode.java
- src/main/java/com/aeon/hadog/base/dto/mypage/MyPageDTO.java
- src/main/java/com/aeon/hadog/base/exception/AdoptReviewNotFoundException.java
- src/main/java/com/aeon/hadog/base/exception/GlobalExceptionHandler.java
- src/main/java/com/aeon/hadog/controller/AdoptReviewController.java
- src/main/java/com/aeon/hadog/controller/MyPageController.java
- src/main/java/com/aeon/hadog/domain/AdoptPost.java
- src/main/java/com/aeon/hadog/repository/AdoptPostRepository.java
- src/main/java/com/aeon/hadog/service/AdoptPostService.java
- src/main/java/com/aeon/hadog/service/MyPageService.java
- src/test/java/com/aeon/hadog/controller/AdoptReviewControllerTest.java
- src/test/java/com/aeon/hadog/controller/MyPageControllerTest.java
- src/test/java/com/aeon/hadog/controller/UserControllerTest.java
- src/test/java/com/aeon/hadog/service/AdoptReviewServiceTest.java
- src/test/java/com/aeon/hadog/service/MyPageServiceTest.java
- 마이페이지에서 입양공고 반환 기능
-  마이페이지와 후기 페이지 테스트 코드 작성
> 입양공고 반환 기능 & 마이페이지, 후기페이지 test

- src/main/java/com/aeon/hadog/service/MyPageService.java
> Feat:반려견반환수정

- src/main/java/com/aeon/hadog/base/dto/pet/PetDTO.java
- src/main/java/com/aeon/hadog/service/MyPageService.java
> FEAT : 반려견 조회 수정

- src/main/java/com/aeon/hadog/base/dto/adoptPost/AdoptPostDTO.java
- src/main/java/com/aeon/hadog/domain/AdoptPost.java
- src/main/java/com/aeon/hadog/service/MyPageService.java
> FEAT: mypage 수정

- src/main/java/com/aeon/hadog/controller/DiaryController.java
- src/main/java/com/aeon/hadog/repository/DiaryRepository.java
- src/main/java/com/aeon/hadog/service/DiaryService.java
다이어리 삭제 및 달별 조회 기능 구현했습니다.
#73 #74
> Feat: 다이어리 삭제 및 달별 조회 기능 구현

- src/main/java/com/aeon/hadog/base/dto/adoptPost/AdoptPostDTO.java
> FEAT:mypage수정

- src/main/java/com/aeon/hadog/service/DiaryService.java
> Refactor: month에 diaryId값 null 해결

- src/main/java/com/aeon/hadog/base/dto/adoptPost/ListAdoptPostDTO.java
- src/main/java/com/aeon/hadog/base/dto/shelter/ListShelterPostDTO.java
- src/main/java/com/aeon/hadog/service/AdoptPostService.java
- src/main/java/com/aeon/hadog/service/ShelterPostService.java
> Refactor: 입양 공고, 보호소 목록에 id값 추가

- src/main/java/com/aeon/hadog/base/dto/adoptPost/AdoptPostDTO.java
Refacotr: AdoptPostDTO postDate 필드 수정
- 입양 공고 작성시, 날짜를 받아올 필요가 없음에도 불구하고 @NotNull때문에 입력을 해주어야했음
- @NotNull 어노테이션 제거
> Refacotr: AdoptPostDTO postDate 필드 수정
